spring:
  cloud:
    config:
      server:
        git:
          search-paths: respo
          uri: https://github.com/forezp/SpringcloudConfig/
          # username: 用户名 # public 不需要用户名和密码
          # password: 密码
      label: master

  application:
    name: config-server
server:
  port: 8768
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

