#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#server:
#  port: 8778
#spring:
#  application:
#    name: product-service

mybatis:
#  check-config-location: false
  type-aliases-package: com.example.common.domain
  mapper-locations: classpath:mapping/*.xml